language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile

rvm: 2.2.2

before_install:
- gem install cocoapods

before_script:
- export LANG=en_US.UTF-8

script: xctool -workspace YaftDB.xcworkspace -scheme YaftDBTests -sdk iphonesimulator test
